# Generated by vmake version 2.0

# Define path to each library
LIB_STD = /usr/pack/modelsim-6.0a-ma/modeltech/sunos5/../std
LIB_IEEE = /usr/pack/modelsim-6.0a-ma/modeltech/sunos5/../ieee
LIB_WORK = work

# Define path to each design unit
IEEE-std_logic_1164 = $(LIB_IEEE)/std_logic_1164/_primary.dat
IEEE-numeric_std = $(LIB_IEEE)/numeric_std/_primary.dat
STD-textio = $(LIB_STD)/textio/_primary.dat
IEEE-std_logic_textio = $(LIB_IEEE)/std_logic_textio/_primary.dat
WORK-zunit-simple = $(LIB_WORK)/zunit/simple.dat
WORK-zunit = $(LIB_WORK)/zunit/_primary.dat
WORK-zarchpkg-body = $(LIB_WORK)/zarchpkg/body.dat
WORK-zarchpkg = $(LIB_WORK)/zarchpkg/_primary.dat
WORK-updowncounter-simple = $(LIB_WORK)/updowncounter/simple.dat
WORK-updowncounter = $(LIB_WORK)/updowncounter/_primary.dat
WORK-upcounter-simple = $(LIB_WORK)/upcounter/simple.dat
WORK-upcounter = $(LIB_WORK)/upcounter/_primary.dat
WORK-txt_util-body = $(LIB_WORK)/txt_util/body.dat
WORK-txt_util = $(LIB_WORK)/txt_util/_primary.dat
WORK-tristatebuf-simple = $(LIB_WORK)/tristatebuf/simple.dat
WORK-tristatebuf = $(LIB_WORK)/tristatebuf/_primary.dat
WORK-schedulestoremem-simple = $(LIB_WORK)/schedulestoremem/simple.dat
WORK-schedulestoremem = $(LIB_WORK)/schedulestoremem/_primary.dat
WORK-schedulestore-simple = $(LIB_WORK)/schedulestore/simple.dat
WORK-schedulestore = $(LIB_WORK)/schedulestore/_primary.dat
WORK-schedulectrl-simple = $(LIB_WORK)/schedulectrl/simple.dat
WORK-schedulectrl = $(LIB_WORK)/schedulectrl/_primary.dat
WORK-row-simple = $(LIB_WORK)/row/simple.dat
WORK-row = $(LIB_WORK)/row/_primary.dat
WORK-routel-simple = $(LIB_WORK)/routel/simple.dat
WORK-routel = $(LIB_WORK)/routel/_primary.dat
WORK-rom-behavioral = $(LIB_WORK)/rom/behavioral.dat
WORK-rom = $(LIB_WORK)/rom/_primary.dat
WORK-reg_en-simple = $(LIB_WORK)/reg_en/simple.dat
WORK-reg_en = $(LIB_WORK)/reg_en/_primary.dat
WORK-reg_clr_en-simple = $(LIB_WORK)/reg_clr_en/simple.dat
WORK-reg_clr_en = $(LIB_WORK)/reg_clr_en/_primary.dat
WORK-reg_aclr_en-simple = $(LIB_WORK)/reg_aclr_en/simple.dat
WORK-reg_aclr_en = $(LIB_WORK)/reg_aclr_en/_primary.dat
WORK-pullbus-behav = $(LIB_WORK)/pullbus/behav.dat
WORK-pullbus = $(LIB_WORK)/pullbus/_primary.dat
WORK-pull-behav = $(LIB_WORK)/pull/behav.dat
WORK-pull = $(LIB_WORK)/pull/_primary.dat
WORK-procel-simple = $(LIB_WORK)/procel/simple.dat
WORK-procel = $(LIB_WORK)/procel/_primary.dat
WORK-mux8to1-simple = $(LIB_WORK)/mux8to1/simple.dat
WORK-mux8to1 = $(LIB_WORK)/mux8to1/_primary.dat
WORK-mux4to1-simple = $(LIB_WORK)/mux4to1/simple.dat
WORK-mux4to1 = $(LIB_WORK)/mux4to1/_primary.dat
WORK-mux2to1-simple = $(LIB_WORK)/mux2to1/simple.dat
WORK-mux2to1 = $(LIB_WORK)/mux2to1/_primary.dat
WORK-mux16to1-simple = $(LIB_WORK)/mux16to1/simple.dat
WORK-mux16to1 = $(LIB_WORK)/mux16to1/_primary.dat
WORK-lookuptable4to1-simple = $(LIB_WORK)/lookuptable4to1/simple.dat
WORK-lookuptable4to1 = $(LIB_WORK)/lookuptable4to1/_primary.dat
WORK-ioportctrl-simple = $(LIB_WORK)/ioportctrl/simple.dat
WORK-ioportctrl = $(LIB_WORK)/ioportctrl/_primary.dat
WORK-iop_compare-simple = $(LIB_WORK)/iop_compare/simple.dat
WORK-iop_compare = $(LIB_WORK)/iop_compare/_primary.dat
WORK-gmux-behav = $(LIB_WORK)/gmux/behav.dat
WORK-gmux = $(LIB_WORK)/gmux/_primary.dat
WORK-flipflop_clr-simple = $(LIB_WORK)/flipflop_clr/simple.dat
WORK-flipflop_clr = $(LIB_WORK)/flipflop_clr/_primary.dat
WORK-flipflop-simple = $(LIB_WORK)/flipflop/simple.dat
WORK-flipflop = $(LIB_WORK)/flipflop/_primary.dat
WORK-fifomem-simple = $(LIB_WORK)/fifomem/simple.dat
WORK-fifomem = $(LIB_WORK)/fifomem/_primary.dat
WORK-fifoctrl-simple = $(LIB_WORK)/fifoctrl/simple.dat
WORK-fifoctrl = $(LIB_WORK)/fifoctrl/_primary.dat
WORK-fifo-simple = $(LIB_WORK)/fifo/simple.dat
WORK-fifo = $(LIB_WORK)/fifo/_primary.dat
WORK-engine-simple = $(LIB_WORK)/engine/simple.dat
WORK-engine = $(LIB_WORK)/engine/_primary.dat
WORK-engclearctrl-simple = $(LIB_WORK)/engclearctrl/simple.dat
WORK-engclearctrl = $(LIB_WORK)/engclearctrl/_primary.dat
WORK-decoder-simple = $(LIB_WORK)/decoder/simple.dat
WORK-decoder = $(LIB_WORK)/decoder/_primary.dat
WORK-cycledncntr-simple = $(LIB_WORK)/cycledncntr/simple.dat
WORK-cycledncntr = $(LIB_WORK)/cycledncntr/_primary.dat
WORK-cyclecntctrl-simple = $(LIB_WORK)/cyclecntctrl/simple.dat
WORK-cyclecntctrl = $(LIB_WORK)/cyclecntctrl/_primary.dat
WORK-contextselctrl-simple = $(LIB_WORK)/contextselctrl/simple.dat
WORK-contextselctrl = $(LIB_WORK)/contextselctrl/_primary.dat
WORK-contextregfile-simple = $(LIB_WORK)/contextregfile/simple.dat
WORK-contextregfile = $(LIB_WORK)/contextregfile/_primary.dat
WORK-contextmux-behav = $(LIB_WORK)/contextmux/behav.dat
WORK-contextmux = $(LIB_WORK)/contextmux/_primary.dat
WORK-configpkg-body = $(LIB_WORK)/configpkg/body.dat
WORK-configpkg = $(LIB_WORK)/configpkg/_primary.dat
WORK-configmem-simple = $(LIB_WORK)/configmem/simple.dat
WORK-configmem = $(LIB_WORK)/configmem/_primary.dat
WORK-componentspkg = $(LIB_WORK)/componentspkg/_primary.dat
WORK-cell-simple = $(LIB_WORK)/cell/simple.dat
WORK-cell = $(LIB_WORK)/cell/_primary.dat
WORK-cclkgating-simple = $(LIB_WORK)/cclkgating/simple.dat
WORK-cclkgating = $(LIB_WORK)/cclkgating/_primary.dat
WORK-auxpkg-body = $(LIB_WORK)/auxpkg/body.dat
WORK-auxpkg = $(LIB_WORK)/auxpkg/_primary.dat
WORK-archconfigpkg-body = $(LIB_WORK)/archconfigpkg/body.dat
WORK-archconfigpkg = $(LIB_WORK)/archconfigpkg/_primary.dat
VCOM = vcom
VLOG = vlog

whole_library :     $(WORK-zunit-simple) \
    $(WORK-zunit) \
    $(WORK-zarchpkg-body) \
    $(WORK-zarchpkg) \
    $(WORK-updowncounter-simple) \
    $(WORK-updowncounter) \
    $(WORK-upcounter-simple) \
    $(WORK-upcounter) \
    $(WORK-txt_util-body) \
    $(WORK-txt_util) \
    $(WORK-tristatebuf-simple) \
    $(WORK-tristatebuf) \
    $(WORK-schedulestoremem-simple) \
    $(WORK-schedulestoremem) \
    $(WORK-schedulestore-simple) \
    $(WORK-schedulestore) \
    $(WORK-schedulectrl-simple) \
    $(WORK-schedulectrl) \
    $(WORK-row-simple) \
    $(WORK-row) \
    $(WORK-routel-simple) \
    $(WORK-routel) \
    $(WORK-rom-behavioral) \
    $(WORK-rom) \
    $(WORK-reg_en-simple) \
    $(WORK-reg_en) \
    $(WORK-reg_clr_en-simple) \
    $(WORK-reg_clr_en) \
    $(WORK-reg_aclr_en-simple) \
    $(WORK-reg_aclr_en) \
    $(WORK-pullbus-behav) \
    $(WORK-pullbus) \
    $(WORK-pull-behav) \
    $(WORK-pull) \
    $(WORK-procel-simple) \
    $(WORK-procel) \
    $(WORK-mux8to1-simple) \
    $(WORK-mux8to1) \
    $(WORK-mux4to1-simple) \
    $(WORK-mux4to1) \
    $(WORK-mux2to1-simple) \
    $(WORK-mux2to1) \
    $(WORK-mux16to1-simple) \
    $(WORK-mux16to1) \
    $(WORK-lookuptable4to1-simple) \
    $(WORK-lookuptable4to1) \
    $(WORK-ioportctrl-simple) \
    $(WORK-ioportctrl) \
    $(WORK-iop_compare-simple) \
    $(WORK-iop_compare) \
    $(WORK-gmux-behav) \
    $(WORK-gmux) \
    $(WORK-flipflop_clr-simple) \
    $(WORK-flipflop_clr) \
    $(WORK-flipflop-simple) \
    $(WORK-flipflop) \
    $(WORK-fifomem-simple) \
    $(WORK-fifomem) \
    $(WORK-fifoctrl-simple) \
    $(WORK-fifoctrl) \
    $(WORK-fifo-simple) \
    $(WORK-fifo) \
    $(WORK-engine-simple) \
    $(WORK-engine) \
    $(WORK-engclearctrl-simple) \
    $(WORK-engclearctrl) \
    $(WORK-decoder-simple) \
    $(WORK-decoder) \
    $(WORK-cycledncntr-simple) \
    $(WORK-cycledncntr) \
    $(WORK-cyclecntctrl-simple) \
    $(WORK-cyclecntctrl) \
    $(WORK-contextselctrl-simple) \
    $(WORK-contextselctrl) \
    $(WORK-contextregfile-simple) \
    $(WORK-contextregfile) \
    $(WORK-contextmux-behav) \
    $(WORK-contextmux) \
    $(WORK-configpkg-body) \
    $(WORK-configpkg) \
    $(WORK-configmem-simple) \
    $(WORK-configmem) \
    $(WORK-componentspkg) \
    $(WORK-cell-simple) \
    $(WORK-cell) \
    $(WORK-cclkgating-simple) \
    $(WORK-cclkgating) \
    $(WORK-auxpkg-body) \
    $(WORK-auxpkg) \
    $(WORK-archconfigpkg-body) \
    $(WORK-archconfigpkg)

$(WORK-archconfigpkg) \
$(WORK-archconfigpkg-body) : archConfigPkg.vhd \
		$(STD-textio) \
		$(WORK-txt_util) \
		$(WORK-auxpkg) \
		$(IEEE-numeric_std) \
		$(IEEE-std_logic_1164)
	$(VCOM) -quiet -93 archConfigPkg.vhd

$(WORK-auxpkg) \
$(WORK-auxpkg-body) : auxPkg.vhd \
		$(STD-textio) \
		$(WORK-txt_util) \
		$(IEEE-std_logic_1164)
	$(VCOM) -lint -quiet -93 -quiet auxPkg.vhd

$(WORK-cclkgating) \
$(WORK-cclkgating-simple) : cclkgating.vhd \
		$(IEEE-numeric_std) \
		$(IEEE-std_logic_1164)
	$(VCOM) -lint -quiet -93 -quiet cclkgating.vhd

$(WORK-cell) \
$(WORK-cell-simple) : cell.vhd \
		$(IEEE-std_logic_textio) \
		$(WORK-configpkg) \
		$(WORK-componentspkg) \
		$(WORK-zarchpkg) \
		$(STD-textio) \
		$(WORK-txt_util) \
		$(WORK-auxpkg) \
		$(WORK-archconfigpkg) \
		$(IEEE-numeric_std) \
		$(IEEE-std_logic_1164)
	$(VCOM) -lint -quiet -93 -quiet cell.vhd

$(WORK-componentspkg) : componentsPkg.vhd \
		$(IEEE-std_logic_textio) \
		$(WORK-configpkg) \
		$(WORK-zarchpkg) \
		$(STD-textio) \
		$(WORK-txt_util) \
		$(WORK-auxpkg) \
		$(WORK-archconfigpkg) \
		$(IEEE-numeric_std) \
		$(IEEE-std_logic_1164)
	$(VCOM) -lint -quiet -93 -quiet componentsPkg.vhd

$(WORK-configmem) \
$(WORK-configmem-simple) : configmem.vhd \
		$(STD-textio) \
		$(WORK-txt_util) \
		$(WORK-auxpkg) \
		$(WORK-archconfigpkg) \
		$(WORK-zarchpkg) \
		$(IEEE-numeric_std) \
		$(IEEE-std_logic_1164)
	$(VCOM) -lint -quiet -93 -quiet configmem.vhd

$(WORK-configpkg) \
$(WORK-configpkg-body) : configPkg.vhd \
		$(WORK-zarchpkg) \
		$(WORK-auxpkg) \
		$(WORK-archconfigpkg) \
		$(WORK-txt_util) \
		$(IEEE-std_logic_textio) \
		$(STD-textio) \
		$(IEEE-numeric_std) \
		$(IEEE-std_logic_1164)
	$(VCOM) -lint -quiet -93 -quiet configPkg.vhd

$(WORK-contextmux) \
$(WORK-contextmux-behav) : contextmux.vhd \
		$(WORK-zarchpkg) \
		$(WORK-auxpkg) \
		$(WORK-archconfigpkg) \
		$(WORK-txt_util) \
		$(IEEE-std_logic_textio) \
		$(STD-textio) \
		$(WORK-configpkg) \
		$(IEEE-numeric_std) \
		$(IEEE-std_logic_1164)
	$(VCOM) -lint -quiet -93 -quiet contextmux.vhd

$(WORK-contextregfile) \
$(WORK-contextregfile-simple) : contextregfile.vhd \
		$(IEEE-std_logic_textio) \
		$(WORK-configpkg) \
		$(WORK-zarchpkg) \
		$(STD-textio) \
		$(WORK-txt_util) \
		$(WORK-auxpkg) \
		$(WORK-archconfigpkg) \
		$(WORK-componentspkg) \
		$(IEEE-numeric_std) \
		$(IEEE-std_logic_1164)
	$(VCOM) -lint -quiet -93 -quiet contextregfile.vhd

$(WORK-contextselctrl) \
$(WORK-contextselctrl-simple) : contextselctrl.vhd \
		$(IEEE-std_logic_1164)
	$(VCOM) -lint -quiet -93 -quiet contextselctrl.vhd

$(WORK-cyclecntctrl) \
$(WORK-cyclecntctrl-simple) : cyclecntctrl.vhd \
		$(IEEE-std_logic_1164)
	$(VCOM) -lint -quiet -93 -quiet cyclecntctrl.vhd

$(WORK-cycledncntr) \
$(WORK-cycledncntr-simple) : cycledncntr.vhd \
		$(IEEE-numeric_std) \
		$(IEEE-std_logic_1164)
	$(VCOM) -lint -quiet -93 -quiet cycledncntr.vhd

$(WORK-decoder) \
$(WORK-decoder-simple) : decoder.vhd \
		$(WORK-zarchpkg) \
		$(STD-textio) \
		$(WORK-txt_util) \
		$(WORK-auxpkg) \
		$(WORK-archconfigpkg) \
		$(IEEE-numeric_std) \
		$(IEEE-std_logic_1164)
	$(VCOM) -lint -quiet -93 -quiet decoder.vhd

$(WORK-engclearctrl) \
$(WORK-engclearctrl-simple) : engclearctrl.vhd \
		$(IEEE-std_logic_1164)
	$(VCOM) -lint -quiet -93 -quiet engclearctrl.vhd

$(WORK-engine) \
$(WORK-engine-simple) : engine.vhd \
		$(IEEE-std_logic_textio) \
		$(WORK-configpkg) \
		$(WORK-componentspkg) \
		$(WORK-zarchpkg) \
		$(STD-textio) \
		$(WORK-txt_util) \
		$(WORK-auxpkg) \
		$(WORK-archconfigpkg) \
		$(IEEE-numeric_std) \
		$(IEEE-std_logic_1164)
	$(VCOM) -lint -quiet -93 -quiet engine.vhd

$(WORK-fifoctrl) \
$(WORK-fifoctrl-simple) : fifoctrl.vhd \
		$(IEEE-std_logic_1164)
	$(VCOM) -lint -quiet -93 -quiet fifoctrl.vhd

$(WORK-fifo) \
$(WORK-fifo-simple) \
$(WORK-fifomem) \
$(WORK-fifomem-simple) : fifo.vhd \
		$(IEEE-std_logic_textio) \
		$(WORK-configpkg) \
		$(WORK-zarchpkg) \
		$(WORK-archconfigpkg) \
		$(WORK-componentspkg) \
		$(STD-textio) \
		$(WORK-txt_util) \
		$(WORK-auxpkg) \
		$(IEEE-numeric_std) \
		$(IEEE-std_logic_1164)
	$(VCOM) -lint -quiet -93 -quiet fifo.vhd

$(WORK-flipflop) \
$(WORK-flipflop-simple) \
$(WORK-flipflop_clr) \
$(WORK-flipflop_clr-simple) : flipflop.vhd \
		$(IEEE-numeric_std) \
		$(IEEE-std_logic_1164)
	$(VCOM) -lint -quiet -93 -quiet flipflop.vhd

$(WORK-iop_compare) \
$(WORK-iop_compare-simple) \
$(WORK-ioportctrl) \
$(WORK-ioportctrl-simple) \
$(WORK-lookuptable4to1) \
$(WORK-lookuptable4to1-simple) : ioportctrl.vhd \
		$(IEEE-std_logic_textio) \
		$(WORK-configpkg) \
		$(WORK-componentspkg) \
		$(STD-textio) \
		$(WORK-txt_util) \
		$(WORK-auxpkg) \
		$(WORK-archconfigpkg) \
		$(WORK-zarchpkg) \
		$(IEEE-numeric_std) \
		$(IEEE-std_logic_1164)
	$(VCOM) -lint -quiet -93 -quiet ioportctrl.vhd

$(WORK-gmux) \
$(WORK-gmux-behav) \
$(WORK-mux16to1) \
$(WORK-mux16to1-simple) \
$(WORK-mux2to1) \
$(WORK-mux2to1-simple) \
$(WORK-mux4to1) \
$(WORK-mux4to1-simple) \
$(WORK-mux8to1) \
$(WORK-mux8to1-simple) : mux.vhd \
		$(STD-textio) \
		$(WORK-txt_util) \
		$(WORK-auxpkg) \
		$(IEEE-numeric_std) \
		$(IEEE-std_logic_1164)
	$(VCOM) -lint -quiet -93 -quiet mux.vhd

$(WORK-procel) \
$(WORK-procel-simple) : procel.vhd \
		$(IEEE-std_logic_textio) \
		$(WORK-configpkg) \
		$(WORK-componentspkg) \
		$(WORK-zarchpkg) \
		$(STD-textio) \
		$(WORK-txt_util) \
		$(WORK-auxpkg) \
		$(WORK-archconfigpkg) \
		$(IEEE-numeric_std) \
		$(IEEE-std_logic_1164)
	$(VCOM) -lint -quiet -93 -quiet procel.vhd

$(WORK-pull) \
$(WORK-pull-behav) \
$(WORK-pullbus) \
$(WORK-pullbus-behav) : pull.vhd \
		$(IEEE-std_logic_textio) \
		$(WORK-configpkg) \
		$(WORK-zarchpkg) \
		$(STD-textio) \
		$(WORK-txt_util) \
		$(WORK-auxpkg) \
		$(WORK-archconfigpkg) \
		$(IEEE-numeric_std) \
		$(WORK-componentspkg) \
		$(IEEE-std_logic_1164)
	$(VCOM) -lint -quiet -93 -quiet pull.vhd

$(WORK-reg_aclr_en) \
$(WORK-reg_aclr_en-simple) \
$(WORK-reg_clr_en) \
$(WORK-reg_clr_en-simple) \
$(WORK-reg_en) \
$(WORK-reg_en-simple) : reg.vhd \
		$(IEEE-std_logic_1164) \
		$(IEEE-numeric_std)
	$(VCOM) -lint -quiet -93 -quiet reg.vhd

$(WORK-rom) \
$(WORK-rom-behavioral) : memory.vhd \
		$(STD-textio) \
		$(WORK-txt_util) \
		$(WORK-auxpkg) \
		$(WORK-archconfigpkg) \
		$(WORK-zarchpkg) \
		$(IEEE-numeric_std) \
		$(IEEE-std_logic_1164)
	$(VCOM) -lint -quiet -93 -quiet memory.vhd

$(WORK-routel) \
$(WORK-routel-simple) : routel.vhd \
		$(IEEE-std_logic_textio) \
		$(WORK-configpkg) \
		$(WORK-componentspkg) \
		$(STD-textio) \
		$(WORK-txt_util) \
		$(WORK-auxpkg) \
		$(WORK-archconfigpkg) \
		$(WORK-zarchpkg) \
		$(IEEE-numeric_std) \
		$(IEEE-std_logic_1164)
	$(VCOM) -lint -quiet -93 -quiet routel.vhd

$(WORK-row) \
$(WORK-row-simple) : row.vhd \
		$(IEEE-std_logic_textio) \
		$(WORK-configpkg) \
		$(WORK-componentspkg) \
		$(WORK-zarchpkg) \
		$(STD-textio) \
		$(WORK-txt_util) \
		$(WORK-auxpkg) \
		$(WORK-archconfigpkg) \
		$(IEEE-numeric_std) \
		$(IEEE-std_logic_1164)
	$(VCOM) -lint -quiet -93 -quiet row.vhd

$(WORK-schedulectrl) \
$(WORK-schedulectrl-simple) : schedulectrl.vhd \
		$(IEEE-std_logic_1164)
	$(VCOM) -lint -quiet -93 -quiet schedulectrl.vhd

$(WORK-schedulestore) \
$(WORK-schedulestore-simple) \
$(WORK-schedulestoremem) \
$(WORK-schedulestoremem-simple) : schedulestore.vhd \
		$(IEEE-std_logic_textio) \
		$(WORK-configpkg) \
		$(WORK-zarchpkg) \
		$(WORK-archconfigpkg) \
		$(WORK-componentspkg) \
		$(STD-textio) \
		$(WORK-txt_util) \
		$(WORK-auxpkg) \
		$(IEEE-numeric_std) \
		$(IEEE-std_logic_1164)
	$(VCOM) -lint -quiet -93 -quiet schedulestore.vhd

$(WORK-tristatebuf) \
$(WORK-tristatebuf-simple) : tristatebuf.vhd \
		$(IEEE-std_logic_1164)
	$(VCOM) -lint -quiet -93 -quiet tristatebuf.vhd

$(WORK-txt_util) \
$(WORK-txt_util-body) : txt_util.vhd \
		$(STD-textio) \
		$(IEEE-std_logic_1164)
	$(VCOM) -lint -quiet -93 -quiet txt_util.vhd

$(WORK-upcounter) \
$(WORK-upcounter-simple) \
$(WORK-updowncounter) \
$(WORK-updowncounter-simple) : counter.vhd \
		$(IEEE-numeric_std) \
		$(IEEE-std_logic_1164)
	$(VCOM) -lint -quiet -93 -quiet counter.vhd

$(WORK-zarchpkg) \
$(WORK-zarchpkg-body) : zarchPkg.vhd \
		$(STD-textio) \
		$(WORK-txt_util) \
		$(WORK-auxpkg) \
		$(WORK-archconfigpkg) \
		$(IEEE-numeric_std) \
		$(IEEE-std_logic_1164)
	$(VCOM) -lint -quiet -93 -quiet zarchPkg.vhd

$(WORK-zunit) \
$(WORK-zunit-simple) : zunit.vhd \
		$(IEEE-std_logic_textio) \
		$(WORK-configpkg) \
		$(WORK-componentspkg) \
		$(WORK-zarchpkg) \
		$(WORK-archconfigpkg) \
		$(STD-textio) \
		$(WORK-txt_util) \
		$(WORK-auxpkg) \
		$(IEEE-numeric_std) \
		$(IEEE-std_logic_1164)
	$(VCOM) -lint -quiet -93 -quiet zunit.vhd
